
# GP Geo CV Tuning

Nested geographic tuning workflow. The expensive cells are restartable: each `(param_id, fold_idx)` fit writes one CSV under `../eval_results/`, and reruns skip completed files.

In [1]:

import json
import os
import subprocess
import sys
import time
from pathlib import Path

import jax.numpy as jnp
import jax.random as jr
import numpy as np
import pandas as pd

CWD = Path.cwd()
if CWD.name == "gridsearch":
    NOTEBOOK_DIR = CWD
elif (CWD / "gridsearch").exists() and CWD.name == "code":
    NOTEBOOK_DIR = CWD / "gridsearch"
elif (CWD / "code" / "gridsearch").exists():
    NOTEBOOK_DIR = CWD / "code" / "gridsearch"
else:
    NOTEBOOK_DIR = CWD
CODE_DIR = NOTEBOOK_DIR.parent

sys.path.append(str(CODE_DIR))

from gp import GaussianProcess
from gp_kernels import make_indoor_outdoor_mean, make_wifi_kernel
from eval_workflow import (
    completed_gp_results,
    load_fold_arrays,
    load_result_index,
    materialize_matching_result,
    summarize_cv_results,
    write_result_row,
)

In [2]:

SPLIT_ROOT = CODE_DIR / "eval_splits" / "geo_outer0"
GRID_PATH = CODE_DIR / "gridsearch" / "gp_geo_stage1_grid.csv"
STAGE1_RESULT_DIR = CODE_DIR / "eval_results" / "gp_stage1"
STAGE2_RESULT_DIR = CODE_DIR / "eval_results" / "gp_stage2"
FINAL_RESULT_PATH = CODE_DIR / "eval_results" / "gp_final_holdout.csv"

STAGE1_FOLDS = 3
STAGE2_FOLDS = 5
STAGE2_TOP_N = 25

N_CHAINS = 2
N_SAMPLES = 111
BURNIN = 10
THIN = 10
CALIBRATION_ITERS = 30
JITTER_FACTOR = 10
PREDICT_METHOD = "sequential"
KEY_SEED = 305


RUN_FITS_IN_SUBPROCESS = True
# Sequential chunking: one subprocess runs this many fits, exits to release GPU memory,
# then the notebook launches the next subprocess. This is not parallel.
FITS_PER_PROCESS = 20
GP_FIT_RUNNER = CODE_DIR / "run_gp_cv_fit.py"
PYTHON_EXECUTABLE = sys.executable

In [3]:

grid = pd.read_csv(GRID_PATH)
grid.shape, grid.head()

((108, 9),
    param_id  ls_xy  ls_z  os_xyz  ls_t  os_t ap_form  ls_ap  os_ap
 0         0  0.025  0.25      20    50     0     add   0.25   10.0
 1         1  0.025  0.25      20    50     0     add   0.25   20.0
 2         2  0.025  0.25      20    50     0     add   0.25   40.0
 3         3  0.025  0.25      20    50     0     add   0.50   10.0
 4         4  0.025  0.25      20    50     0     add   0.50   20.0)

In [4]:

def format_seconds(seconds):
    seconds = int(round(float(seconds)))
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours}h {minutes:02d}m {seconds:02d}s"
    if minutes:
        return f"{minutes}m {seconds:02d}s"
    return f"{seconds}s"


def print_loop_progress(stage_label, completed_count, total_count, loop_start, session_completed):
    elapsed = time.time() - loop_start
    avg = elapsed / max(session_completed, 1)
    remaining = max(total_count - completed_count, 0)
    eta = avg * remaining if session_completed else float("nan")
    eta_text = format_seconds(eta) if session_completed else "unknown"
    print(
        f"{stage_label} progress: {completed_count}/{total_count} complete; "
        f"session elapsed {format_seconds(elapsed)}; "
        f"avg/new fit {format_seconds(avg)}; ETA {eta_text}",
        flush=True,
    )


def count_completed_fits(param_grid, n_folds, result_dir, result_index):
    count = 0
    for _, param_row in param_grid.iterrows():
        for fold_idx in range(n_folds):
            count += materialize_matching_result(result_dir, param_row, fold_idx, result_index) is not None
    return int(count)


def pending_jobs(param_grid, n_folds, result_dir, result_index):
    jobs = []
    for _, param_row in param_grid.iterrows():
        param_id = int(param_row["param_id"])
        for fold_idx in range(n_folds):
            if materialize_matching_result(result_dir, param_row, fold_idx, result_index) is None:
                jobs.append({"param_id": param_id, "fold_idx": int(fold_idx)})
    return jobs


def job_chunks(jobs, chunk_size):
    for start in range(0, len(jobs), int(chunk_size)):
        yield jobs[start:start + int(chunk_size)]


def run_fit_chunk(stage_label, chunk, split_dir, result_dir):
    # subprocess.run is blocking, so chunks run sequentially: at most one GPU process.
    cmd = [
        PYTHON_EXECUTABLE,
        str(GP_FIT_RUNNER),
        "--grid-path", str(GRID_PATH),
        "--split-dir", str(split_dir),
        "--result-dir", str(result_dir),
        "--jobs-json", json.dumps(chunk),
        "--chains", str(N_CHAINS),
        "--samples", str(N_SAMPLES),
        "--burnin", str(BURNIN),
        "--thin", str(THIN),
        "--calibration-iters", str(CALIBRATION_ITERS),
        "--jitter-factor", str(JITTER_FACTOR),
        "--predict-method", PREDICT_METHOD,
        "--key-seed", str(KEY_SEED),
    ]
    env = os.environ.copy()
    env.setdefault("XLA_PYTHON_CLIENT_PREALLOCATE", "false")
    env.setdefault("XLA_PYTHON_CLIENT_ALLOCATOR", "platform")
    print(
        f"{stage_label}: launching one subprocess for {len(chunk)} fit(s): "
        f"param {chunk[0]['param_id']} fold {chunk[0]['fold_idx']} -> "
        f"param {chunk[-1]['param_id']} fold {chunk[-1]['fold_idx']}",
        flush=True,
    )
    subprocess.run(cmd, check=True, env=env)


def run_stage_loop(stage_label, param_grid, n_folds, split_dir, result_dir):
    total = len(param_grid) * n_folds
    result_index = load_result_index(result_dir)
    completed_count = count_completed_fits(param_grid, n_folds, result_dir, result_index)
    jobs = pending_jobs(param_grid, n_folds, result_dir, result_index)
    loop_start = time.time()
    session_completed = 0
    print(f"Completed {completed_count} / {total} {stage_label.lower()} fits")

    if RUN_FITS_IN_SUBPROCESS:
        for chunk in job_chunks(jobs, FITS_PER_PROCESS):
            run_fit_chunk(stage_label, chunk, split_dir, result_dir)
            session_completed += len(chunk)
            completed_count += len(chunk)
            print_loop_progress(stage_label, completed_count, total, loop_start, session_completed)
        return

    for job in jobs:
        param_row = param_grid.loc[param_grid["param_id"] == job["param_id"]].iloc[0]
        print(f"{stage_label} param {job['param_id']} fold {job['fold_idx']}", flush=True)
        row = fit_evaluate_gp(param_row, split_dir, job["fold_idx"], result_dir)
        session_completed += 1
        completed_count += 1
        print(
            f"{stage_label} fit timing: total={format_seconds(row['total_elapsed'])}, "
            f"gibbs={format_seconds(row['fit_elapsed'])}, "
            f"predict={format_seconds(row['predict_elapsed'])}, mse={row['mse']:.4f}",
            flush=True,
        )
        print_loop_progress(stage_label, completed_count, total, loop_start, session_completed)


def fit_evaluate_gp(param_row, split_dir, fold_idx, result_dir):
    param_id = int(param_row["param_id"])
    completed_row = materialize_matching_result(result_dir, param_row, fold_idx)
    if completed_row is not None:
        return completed_row

    total_start = time.time()
    arrays = load_fold_arrays(split_dir, fold_idx)
    X_train = jnp.asarray(arrays["X_train"])
    y_train = jnp.asarray(arrays["y_train"])
    obs_count_train = jnp.asarray(arrays["obs_count_train"])
    obs_sse_train = jnp.asarray(arrays["obs_sse_train"])
    X_test = jnp.asarray(arrays["X_test"])
    y_test = jnp.asarray(arrays["y_test"])

    m = make_indoor_outdoor_mean(X_train, y_train)
    K = make_wifi_kernel(
        ap_form=param_row["ap_form"],
        ls_xy=param_row["ls_xy"],
        ls_z=param_row["ls_z"],
        os_xyz=param_row["os_xyz"],
        ls_t=param_row["ls_t"],
        os_t=param_row["os_t"],
        ls_ap=param_row["ls_ap"],
        os_ap=param_row["os_ap"],
    )

    gp = GaussianProcess(m, K)
    gp.fit(X_train, y_train, obs_count_train, obs_sse=obs_sse_train)

    start = time.time()
    chain = gp.gibbs(
        key=jr.PRNGKey(KEY_SEED + 1000 * param_id + fold_idx),
        chains=N_CHAINS,
        samples=N_SAMPLES,
        calibration_iters=CALIBRATION_ITERS,
        jitter_factor=JITTER_FACTOR,
    )
    fit_elapsed = time.time() - start

    cov_chains = chain[1][:, BURNIN::THIN, :]
    start = time.time()
    pred_means, pred_vars = gp.predict(X_test, cov_chains, method=PREDICT_METHOD)
    predict_elapsed = time.time() - start

    y_hat = pred_means.mean(axis=0)
    mse = float(jnp.mean((y_test - y_hat) ** 2))

    row = {
        "param_id": param_id,
        "fold_idx": int(fold_idx),
        "n_train": int(X_train.shape[0]),
        "n_test": int(X_test.shape[0]),
        "mse": mse,
        "fit_elapsed": float(fit_elapsed),
        "predict_elapsed": float(predict_elapsed),
        "total_elapsed": float(time.time() - total_start),
        "jitter": float(gp.jitter),
        **{col: param_row[col] for col in ["ap_form", "ls_xy", "ls_z", "os_xyz", "ls_t", "os_t", "ls_ap", "os_ap"]},
    }
    write_result_row(out_path, row)
    return row

In [5]:

# Expensive: stage-1 3-fold GP CV over all configs. Restartable.
stage1_split_dir = SPLIT_ROOT / "inner_geo3"
run_stage_loop("Stage 1", grid, STAGE1_FOLDS, stage1_split_dir, STAGE1_RESULT_DIR)

Completed 0 / 324 stage 1 fits
Stage 1: launching one subprocess for 20 fit(s): param 0 fold 0 -> param 6 fold 1
Worker starting 20 fit(s)
Worker fit 1/20: param 0 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0000_fold_0.csv mse=107.3191 total=10.5s
Worker fit 2/20: param 0 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0000_fold_1.csv mse=84.6518 total=8.5s
Worker fit 3/20: param 0 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0000_fold_2.csv mse=78.4593 total=8.9s
Worker fit 4/20: param 1 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0001_fold_0.csv mse=109.5895 total=5.7s
Worker fit 5/20: param 1 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0001_fold_1.csv mse=nan total=5.2s
Worker fit 6/20: param 1 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0001_fold_2.csv mse=84.0176 total=5.4s
Worker fit 7/20: param 2 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0002_fold_0.csv mse=112.3337 total=5.4s
Worker fit 8/20: param 2 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0002_fold_1.csv mse=91.1708 total=5.0s
Worker fit 9/20: param 2 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0002_fold_2.csv mse=89.6038 total=5.2s
Worker fit 10/20: param 3 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0003_fold_0.csv mse=108.7254 total=5.4s
Worker fit 11/20: param 3 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0003_fold_1.csv mse=85.7992 total=4.9s
Worker fit 12/20: param 3 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0003_fold_2.csv mse=78.5344 total=5.2s
Worker fit 13/20: param 4 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0004_fold_0.csv mse=110.6880 total=5.4s
Worker fit 14/20: param 4 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0004_fold_1.csv mse=88.6310 total=4.9s
Worker fit 15/20: param 4 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0004_fold_2.csv mse=84.3215 total=5.2s
Worker fit 16/20: param 5 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0005_fold_0.csv mse=112.9466 total=5.4s
Worker fit 17/20: param 5 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0005_fold_1.csv mse=92.3018 total=5.0s
Worker fit 18/20: param 5 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0005_fold_2.csv mse=89.9955 total=5.2s
Worker fit 19/20: param 6 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0006_fold_0.csv mse=109.0477 total=5.4s
Worker fit 20/20: param 6 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0006_fold_1.csv mse=85.2237 total=5.0s
Worker finished in 120.3s
Stage 1 progress: 20/324 complete; session elapsed 2m 03s; avg/new fit 6s; ETA 31m 06s
Stage 1: launching one subprocess for 20 fit(s): param 6 fold 2 -> param 13 fold 0
Worker starting 20 fit(s)
Worker fit 1/20: param 6 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0006_fold_2.csv mse=78.3911 total=10.3s
Worker fit 2/20: param 7 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0007_fold_0.csv mse=111.3460 total=9.2s
Worker fit 3/20: param 7 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0007_fold_1.csv mse=87.9574 total=8.5s
Worker fit 4/20: param 7 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0007_fold_2.csv mse=84.0927 total=5.2s
Worker fit 5/20: param 8 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0008_fold_0.csv mse=114.3840 total=5.4s
Worker fit 6/20: param 8 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0008_fold_1.csv mse=91.7286 total=4.9s
Worker fit 7/20: param 8 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0008_fold_2.csv mse=89.7585 total=5.2s
Worker fit 8/20: param 9 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0009_fold_0.csv mse=110.4460 total=5.4s
Worker fit 9/20: param 9 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0009_fold_1.csv mse=86.4103 total=4.9s
Worker fit 10/20: param 9 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0009_fold_2.csv mse=78.4513 total=5.3s
Worker fit 11/20: param 10 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0010_fold_0.csv mse=112.4673 total=5.4s
Worker fit 12/20: param 10 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0010_fold_1.csv mse=89.1808 total=4.9s
Worker fit 13/20: param 10 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0010_fold_2.csv mse=84.3722 total=5.2s
Worker fit 14/20: param 11 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0011_fold_0.csv mse=115.2002 total=5.4s
Worker fit 15/20: param 11 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0011_fold_1.csv mse=93.0312 total=4.9s
Worker fit 16/20: param 11 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0011_fold_2.csv mse=90.2350 total=5.2s
Worker fit 17/20: param 12 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0012_fold_0.csv mse=116.8848 total=5.4s
Worker fit 18/20: param 12 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0012_fold_1.csv mse=89.0539 total=5.0s
Worker fit 19/20: param 12 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0012_fold_2.csv mse=79.6241 total=5.2s
Worker fit 20/20: param 13 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0013_fold_0.csv mse=119.8119 total=5.4s
Worker finished in 119.4s
Stage 1 progress: 40/324 complete; session elapsed 4m 05s; avg/new fit 6s; ETA 28m 58s
Stage 1: launching one subprocess for 20 fit(s): param 13 fold 1 -> param 19 fold 2
Worker starting 20 fit(s)
Worker fit 1/20: param 13 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0013_fold_1.csv mse=91.7710 total=9.8s
Worker fit 2/20: param 13 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0013_fold_2.csv mse=85.6155 total=9.0s
Worker fit 3/20: param 14 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0014_fold_0.csv mse=123.1159 total=9.3s
Worker fit 4/20: param 14 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0014_fold_1.csv mse=95.8255 total=4.9s
Worker fit 5/20: param 14 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0014_fold_2.csv mse=91.9227 total=5.1s
Worker fit 6/20: param 15 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0015_fold_0.csv mse=118.1723 total=5.5s
Worker fit 7/20: param 15 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0015_fold_1.csv mse=90.5488 total=5.0s
Worker fit 8/20: param 15 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0015_fold_2.csv mse=79.7604 total=5.1s
Worker fit 9/20: param 16 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0016_fold_0.csv mse=120.9392 total=5.5s
Worker fit 10/20: param 16 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0016_fold_1.csv mse=93.2448 total=4.9s
Worker fit 11/20: param 16 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0016_fold_2.csv mse=85.9878 total=5.1s
Worker fit 12/20: param 17 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0017_fold_0.csv mse=123.9385 total=5.5s
Worker fit 13/20: param 17 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0017_fold_1.csv mse=97.4510 total=5.0s
Worker fit 14/20: param 17 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0017_fold_2.csv mse=92.3504 total=5.2s
Worker fit 15/20: param 18 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0018_fold_0.csv mse=107.1791 total=5.5s
Worker fit 16/20: param 18 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0018_fold_1.csv mse=84.8748 total=5.0s
Worker fit 17/20: param 18 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0018_fold_2.csv mse=78.5438 total=5.2s
Worker fit 18/20: param 19 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0019_fold_0.csv mse=109.4348 total=5.8s
Worker fit 19/20: param 19 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0019_fold_1.csv mse=87.4911 total=5.3s
Worker fit 20/20: param 19 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0019_fold_2.csv mse=84.0955 total=5.4s
Worker finished in 120.0s
Stage 1 progress: 60/324 complete; session elapsed 6m 07s; avg/new fit 6s; ETA 26m 56s
Stage 1: launching one subprocess for 20 fit(s): param 20 fold 0 -> param 26 fold 1
Worker starting 20 fit(s)
Worker fit 1/20: param 20 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0020_fold_0.csv mse=112.3111 total=10.4s
Worker fit 2/20: param 20 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0020_fold_1.csv mse=91.3461 total=8.5s
Worker fit 3/20: param 20 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0020_fold_2.csv mse=89.5942 total=9.0s
Worker fit 4/20: param 21 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0021_fold_0.csv mse=108.8121 total=5.4s
Worker fit 5/20: param 21 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0021_fold_1.csv mse=85.9057 total=4.9s
Worker fit 6/20: param 21 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0021_fold_2.csv mse=78.8622 total=5.2s
Worker fit 7/20: param 22 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0022_fold_0.csv mse=110.7039 total=5.7s
Worker fit 8/20: param 22 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0022_fold_1.csv mse=88.5180 total=5.2s
Worker fit 9/20: param 22 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0022_fold_2.csv mse=84.5552 total=5.4s
Worker fit 10/20: param 23 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0023_fold_0.csv mse=112.9985 total=5.4s
Worker fit 11/20: param 23 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0023_fold_1.csv mse=92.4172 total=4.9s
Worker fit 12/20: param 23 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0023_fold_2.csv mse=90.0665 total=5.2s
Worker fit 13/20: param 24 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0024_fold_0.csv mse=108.7284 total=5.4s
Worker fit 14/20: param 24 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0024_fold_1.csv mse=85.6368 total=5.0s
Worker fit 15/20: param 24 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0024_fold_2.csv mse=78.5115 total=5.2s
Worker fit 16/20: param 25 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0025_fold_0.csv mse=111.3106 total=5.4s
Worker fit 17/20: param 25 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0025_fold_1.csv mse=88.2716 total=4.9s
Worker fit 18/20: param 25 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0025_fold_2.csv mse=84.2088 total=5.2s
Worker fit 19/20: param 26 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0026_fold_0.csv mse=114.2389 total=5.4s
Worker fit 20/20: param 26 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0026_fold_1.csv mse=92.0127 total=5.0s
Worker finished in 120.1s
Stage 1 progress: 80/324 complete; session elapsed 8m 10s; avg/new fit 6s; ETA 24m 54s
Stage 1: launching one subprocess for 20 fit(s): param 26 fold 2 -> param 33 fold 0
Worker starting 20 fit(s)
Worker fit 1/20: param 26 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0026_fold_2.csv mse=89.8285 total=10.1s
Worker fit 2/20: param 27 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0027_fold_0.csv mse=110.1446 total=9.2s
Worker fit 3/20: param 27 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0027_fold_1.csv mse=86.6595 total=8.5s
Worker fit 4/20: param 27 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0027_fold_2.csv mse=78.7958 total=5.1s
Worker fit 5/20: param 28 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0028_fold_0.csv mse=112.5215 total=5.4s
Worker fit 6/20: param 28 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0028_fold_1.csv mse=89.4507 total=5.1s
Worker fit 7/20: param 28 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0028_fold_2.csv mse=84.4766 total=5.2s
Worker fit 8/20: param 29 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0029_fold_0.csv mse=114.8103 total=5.4s
Worker fit 9/20: param 29 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0029_fold_1.csv mse=93.1351 total=5.0s
Worker fit 10/20: param 29 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0029_fold_2.csv mse=90.3633 total=5.2s
Worker fit 11/20: param 30 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0030_fold_0.csv mse=116.2304 total=5.7s
Worker fit 12/20: param 30 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0030_fold_1.csv mse=89.7998 total=5.0s
Worker fit 13/20: param 30 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0030_fold_2.csv mse=79.8667 total=5.2s
Worker fit 14/20: param 31 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0031_fold_0.csv mse=118.8105 total=5.5s
Worker fit 15/20: param 31 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0031_fold_1.csv mse=92.5675 total=5.0s
Worker fit 16/20: param 31 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0031_fold_2.csv mse=85.9943 total=5.3s
Worker fit 17/20: param 32 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0032_fold_0.csv mse=122.5943 total=5.5s
Worker fit 18/20: param 32 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0032_fold_1.csv mse=nan total=5.0s
Worker fit 19/20: param 32 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0032_fold_2.csv mse=92.0859 total=5.1s
Worker fit 20/20: param 33 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0033_fold_0.csv mse=117.6693 total=5.4s
Worker finished in 120.4s
Stage 1 progress: 100/324 complete; session elapsed 10m 13s; avg/new fit 6s; ETA 22m 52s
Stage 1: launching one subprocess for 20 fit(s): param 33 fold 1 -> param 39 fold 2
Worker starting 20 fit(s)
Worker fit 1/20: param 33 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0033_fold_1.csv mse=90.8854 total=9.9s
Worker fit 2/20: param 33 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0033_fold_2.csv mse=80.0356 total=9.0s
Worker fit 3/20: param 34 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0034_fold_0.csv mse=120.4379 total=9.4s
Worker fit 4/20: param 34 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0034_fold_1.csv mse=93.8364 total=4.9s
Worker fit 5/20: param 34 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0034_fold_2.csv mse=86.2729 total=5.1s
Worker fit 6/20: param 35 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0035_fold_0.csv mse=123.4873 total=5.5s
Worker fit 7/20: param 35 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0035_fold_1.csv mse=97.8442 total=4.9s
Worker fit 8/20: param 35 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0035_fold_2.csv mse=92.6955 total=5.1s
Worker fit 9/20: param 36 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0036_fold_0.csv mse=106.8043 total=5.4s
Worker fit 10/20: param 36 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0036_fold_1.csv mse=85.5113 total=4.9s
Worker fit 11/20: param 36 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage1/param_0036_fold_2.csv mse=74.4117 total=5.1s
Worker fit 12/20: param 37 fold 0

In [6]:

stage1_results = completed_gp_results(STAGE1_RESULT_DIR, grid)
stage1_summary = summarize_cv_results(stage1_results)
stage1_summary = stage1_summary.merge(grid, on="param_id", how="left")
stage1_complete = stage1_summary[stage1_summary["n_folds"] == STAGE1_FOLDS].copy()
stage1_summary.head(25)

,param_id,mean_mse,std_mse,n_folds,mean_fit_elapsed,mean_predict_elapsed,mean_total_elapsed,ls_xy,ls_z,os_xyz,ls_t,os_t,ap_form,ls_ap,os_ap
0,36,88.909093,16.461432,3,4.365819,0.679917,5.152366,0.035,0.25,20,50,0,add,0.25,10.0
1,54,89.042076,16.407107,3,4.944210,0.991316,6.422425,0.035,0.50,20,50,0,add,0.25,10.0
2,72,89.534884,16.214233,3,4.385564,0.674100,5.164043,0.040,0.25,20,50,0,add,0.25,10.0
3,90,89.571940,16.210778,3,4.383437,0.679755,5.169148,0.040,0.50,20,50,0,add,0.25,10.0
4,39,89.585419,16.993128,3,4.389339,0.688039,5.184214,0.035,0.25,20,50,0,add,0.50,10.0
5,42,89.653496,17.591657,3,4.438399,0.719214,5.264047,0.035,0.25,25,50,0,add,0.25,10.0
6,57,89.692713,16.994261,3,4.401121,0.661619,5.167560,0.035,0.50,20,50,0,add,0.50,10.0
7,60,89.833837,17.514991,3,6.299276,1.680989,9.366570,0.035,0.50,25,50,0,add,0.25,10.0
8,75,89.984528,16.737646,3,4.382577,0.685301,5.173503,0.040,0.25,20,50,0,add,0.50,10.0
9,93,90.095673,16.757307,3,5.788617,1.362619,8.158262,0.040,0.50,20,50,0,add,0.50,10.0
10,0,90.143384,15.193444,3,6.263033,1.669576,9.304725,0.025,0.25,20,50,0,add,0.25,10.0
11,18,90.199221,15.041872,3,4.415593,0.677109,5.196830,0.025,0.50,20,50,0,add,0.25,10.0
12,45,90.336820,18.252419,3,4.384131,0.706161,5.197082,0.035,0.25,25,50,0,add,0.50,10.0
13,63,90.452283,18.150748,3,4.385832,0.713777,5.203996,0.035,0.50,25,50,0,add,0.50,10.0
14,78,90.497800,17.545547,3,4.376407,0.678903,5.163753,0.040,0.25,25,50,0,add,0.25,10.0
15,96,90.518283,17.323867,3,4.439773,0.703494,5.248993,0.040,0.50,25,50,0,add,0.25,10.0
16,6,90.887505,16.093977,3,5.232162,1.053627,6.892489,0.025,0.25,25,50,0,add,0.25,10.0
17,24,90.958931,15.795862,3,4.400377,0.684073,5.191171,0.025,0.50,25,50,0,add,0.25,10.0
18,81,90.986415,18.083197,3,4.375732,0.682366,5.165020,0.040,0.25,25,50,0,add,0.50,10.0
19,3,91.019684,15.758004,3,4.384995,0.708352,5.198013,0.025,0.25,20,50,0,add,0.50,10.0
20,99,91.059812,18.046826,3,4.478208,0.705724,5.292358,0.040,0.50,25,50,0,add,0.50,10.0
21,21,91.193354,15.659468,3,4.376950,0.676926,5.155548,0.025,0.50,20,50,0,add,0.50,10.0
22,9,91.769224,16.656945,3,4.380716,0.696614,5.179616,0.025,0.25,25,50,0,add,0.50,10.0
23,27,91.866615,16.310194,3,5.422944,1.310209,7.611060,0.025,0.50,25,50,0,add,0.50,10.0
24,37,92.464877,14.685249,3,4.396899,0.861534,5.480513,0.035,0.25,20,50,0,add,0.25,20.0

In [7]:

if len(stage1_complete) < STAGE2_TOP_N:
    raise RuntimeError(
        f"Need {STAGE2_TOP_N} complete stage-1 configs before stage 2; "
        f"found {len(stage1_complete)}."
    )
stage2_param_ids = stage1_complete.head(STAGE2_TOP_N)["param_id"].astype(int).to_list()
stage2_grid = grid[grid["param_id"].isin(stage2_param_ids)].copy()
stage2_grid

    param_id  ls_xy  ls_z  os_xyz  ls_t  os_t ap_form  ls_ap  os_ap
0          0  0.025  0.25      20    50     0     add   0.25   10.0
3          3  0.025  0.25      20    50     0     add   0.50   10.0
6          6  0.025  0.25      25    50     0     add   0.25   10.0
9          9  0.025  0.25      25    50     0     add   0.50   10.0
18        18  0.025  0.50      20    50     0     add   0.25   10.0
21        21  0.025  0.50      20    50     0     add   0.50   10.0
24        24  0.025  0.50      25    50     0     add   0.25   10.0
27        27  0.025  0.50      25    50     0     add   0.50   10.0
36        36  0.035  0.25      20    50     0     add   0.25   10.0
37        37  0.035  0.25      20    50     0     add   0.25   20.0
39        39  0.035  0.25      20    50     0     add   0.50   10.0
42        42  0.035  0.25      25    50     0     add   0.25   10.0
45        45  0.035  0.25      25    50     0     add   0.50   10.0
54        54  0.035  0.50      20    50     0     add   0.25   10.0
57        57  0.035  0.50      20    50     0     add   0.50   10.0
60        60  0.035  0.50      25    50     0     add   0.25   10.0
63        63  0.035  0.50      25    50     0     add   0.50   10.0
72        72  0.040  0.25      20    50     0     add   0.25   10.0
75        75  0.040  0.25      20    50     0     add   0.50   10.0
78        78  0.040  0.25      25    50     0     add   0.25   10.0
81        81  0.040  0.25      25    50     0     add   0.50   10.0
90        90  0.040  0.50      20    50     0     add   0.25   10.0
93        93  0.040  0.50      20    50     0     add   0.50   10.0
96        96  0.040  0.50      25    50     0     add   0.25   10.0
99        99  0.040  0.50      25    50     0     add   0.50   10.0

In [8]:

# Expensive: stage-2 5-fold GP CV over the top 25 stage-1 configs. Restartable.
stage2_split_dir = SPLIT_ROOT / "inner_geo5"
run_stage_loop("Stage 2", stage2_grid, STAGE2_FOLDS, stage2_split_dir, STAGE2_RESULT_DIR)

Completed 0 / 125 stage 2 fits
Stage 2: launching one subprocess for 20 fit(s): param 0 fold 0 -> param 9 fold 4
Worker starting 20 fit(s)
Worker fit 1/20: param 0 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0000_fold_0.csv mse=84.2933 total=11.4s
Worker fit 2/20: param 0 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0000_fold_1.csv mse=133.1027 total=9.7s
Worker fit 3/20: param 0 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0000_fold_2.csv mse=79.0707 total=9.2s
Worker fit 4/20: param 0 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0000_fold_3.csv mse=71.6227 total=10.0s
Worker fit 5/20: param 0 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0000_fold_4.csv mse=74.1598 total=10.2s
Worker fit 6/20: param 3 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0003_fold_0.csv mse=82.7387 total=5.9s
Worker fit 7/20: param 3 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0003_fold_1.csv mse=137.1713 total=5.8s
Worker fit 8/20: param 3 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0003_fold_2.csv mse=79.0854 total=5.7s
Worker fit 9/20: param 3 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0003_fold_3.csv mse=71.5408 total=6.0s
Worker fit 10/20: param 3 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0003_fold_4.csv mse=75.3047 total=6.1s
Worker fit 11/20: param 6 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0006_fold_0.csv mse=84.8222 total=5.9s
Worker fit 12/20: param 6 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0006_fold_1.csv mse=138.5898 total=6.0s
Worker fit 13/20: param 6 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0006_fold_2.csv mse=79.8115 total=5.6s
Worker fit 14/20: param 6 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0006_fold_3.csv mse=72.3866 total=6.1s
Worker fit 15/20: param 6 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0006_fold_4.csv mse=73.9841 total=6.1s
Worker fit 16/20: param 9 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0009_fold_0.csv mse=83.1412 total=6.0s
Worker fit 17/20: param 9 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0009_fold_1.csv mse=142.3715 total=5.9s
Worker fit 18/20: param 9 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0009_fold_2.csv mse=80.0324 total=5.8s
Worker fit 19/20: param 9 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0009_fold_3.csv mse=72.2926 total=6.0s
Worker fit 20/20: param 9 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0009_fold_4.csv mse=75.1561 total=6.1s
Worker finished in 142.8s
Stage 2 progress: 20/125 complete; session elapsed 2m 24s; avg/new fit 7s; ETA 12m 35s
Stage 2: launching one subprocess for 20 fit(s): param 18 fold 0 -> param 27 fold 4
Worker starting 20 fit(s)
Worker fit 1/20: param 18 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0018_fold_0.csv mse=84.4064 total=11.5s
Worker fit 2/20: param 18 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0018_fold_1.csv mse=133.1493 total=9.6s
Worker fit 3/20: param 18 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0018_fold_2.csv mse=79.2097 total=9.1s
Worker fit 4/20: param 18 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0018_fold_3.csv mse=71.9132 total=9.8s
Worker fit 5/20: param 18 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0018_fold_4.csv mse=74.1420 total=10.2s
Worker fit 6/20: param 21 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0021_fold_0.csv mse=82.7713 total=5.8s
Worker fit 7/20: param 21 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0021_fold_1.csv mse=137.1619 total=5.9s
Worker fit 8/20: param 21 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0021_fold_2.csv mse=79.2408 total=5.5s
Worker fit 9/20: param 21 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0021_fold_3.csv mse=71.7481 total=6.0s
Worker fit 10/20: param 21 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0021_fold_4.csv mse=75.4485 total=6.0s
Worker fit 11/20: param 24 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0024_fold_0.csv mse=84.8925 total=5.8s
Worker fit 12/20: param 24 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0024_fold_1.csv mse=138.2495 total=5.8s
Worker fit 13/20: param 24 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0024_fold_2.csv mse=80.0645 total=5.6s
Worker fit 14/20: param 24 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0024_fold_3.csv mse=72.7047 total=6.0s
Worker fit 15/20: param 24 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0024_fold_4.csv mse=74.0371 total=6.0s
Worker fit 16/20: param 27 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0027_fold_0.csv mse=83.2000 total=5.8s
Worker fit 17/20: param 27 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0027_fold_1.csv mse=142.3990 total=5.8s
Worker fit 18/20: param 27 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0027_fold_2.csv mse=80.2447 total=5.6s
Worker fit 19/20: param 27 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0027_fold_3.csv mse=72.5261 total=6.0s
Worker fit 20/20: param 27 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0027_fold_4.csv mse=75.1698 total=6.1s
Worker finished in 141.5s
Stage 2 progress: 40/125 complete; session elapsed 4m 46s; avg/new fit 7s; ETA 10m 08s
Stage 2: launching one subprocess for 20 fit(s): param 36 fold 0 -> param 42 fold 4
Worker starting 20 fit(s)
Worker fit 1/20: param 36 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0036_fold_0.csv mse=87.4068 total=11.4s
Worker fit 2/20: param 36 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0036_fold_1.csv mse=120.6546 total=9.6s
Worker fit 3/20: param 36 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0036_fold_2.csv mse=82.9060 total=9.2s
Worker fit 4/20: param 36 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0036_fold_3.csv mse=73.1025 total=9.8s
Worker fit 5/20: param 36 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0036_fold_4.csv mse=72.3357 total=10.2s
Worker fit 6/20: param 37 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0037_fold_0.csv mse=91.2636 total=6.1s
Worker fit 7/20: param 37 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0037_fold_1.csv mse=121.9275 total=6.0s
Worker fit 8/20: param 37 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0037_fold_2.csv mse=86.1347 total=5.8s
Worker fit 9/20: param 37 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0037_fold_3.csv mse=77.2823 total=6.3s
Worker fit 10/20: param 37 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0037_fold_4.csv mse=78.5064 total=6.4s
Worker fit 11/20: param 39 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0039_fold_0.csv mse=86.4190 total=6.0s
Worker fit 12/20: param 39 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0039_fold_1.csv mse=123.0773 total=5.8s
Worker fit 13/20: param 39 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0039_fold_2.csv mse=82.8301 total=5.7s
Worker fit 14/20: param 39 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0039_fold_3.csv mse=72.6902 total=6.0s
Worker fit 15/20: param 39 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0039_fold_4.csv mse=73.2024 total=6.2s
Worker fit 16/20: param 42 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0042_fold_0.csv mse=88.4830 total=5.8s
Worker fit 17/20: param 42 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0042_fold_1.csv mse=124.4798 total=5.9s
Worker fit 18/20: param 42 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0042_fold_2.csv mse=84.4380 total=5.6s
Worker fit 19/20: param 42 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0042_fold_3.csv mse=74.2386 total=6.1s
Worker fit 20/20: param 42 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0042_fold_4.csv mse=72.5673 total=6.1s
Worker finished in 143.5s
Stage 2 progress: 60/125 complete; session elapsed 7m 11s; avg/new fit 7s; ETA 7m 47s
Stage 2: launching one subprocess for 20 fit(s): param 45 fold 0 -> param 60 fold 4
Worker starting 20 fit(s)
Worker fit 1/20: param 45 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0045_fold_0.csv mse=87.6890 total=11.4s
Worker fit 2/20: param 45 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0045_fold_1.csv mse=127.3915 total=9.6s
Worker fit 3/20: param 45 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0045_fold_2.csv mse=84.4338 total=9.3s
Worker fit 4/20: param 45 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0045_fold_3.csv mse=73.9126 total=9.8s
Worker fit 5/20: param 45 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0045_fold_4.csv mse=73.3932 total=10.4s
Worker fit 6/20: param 54 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0054_fold_0.csv mse=86.9811 total=5.8s
Worker fit 7/20: param 54 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0054_fold_1.csv mse=120.4257 total=5.9s
Worker fit 8/20: param 54 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0054_fold_2.csv mse=83.1582 total=5.6s
Worker fit 9/20: param 54 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0054_fold_3.csv mse=73.4220 total=6.0s
Worker fit 10/20: param 54 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0054_fold_4.csv mse=72.5117 total=6.0s
Worker fit 11/20: param 57 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0057_fold_0.csv mse=86.2252 total=5.8s
Worker fit 12/20: param 57 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0057_fold_1.csv mse=123.0255 total=5.7s
Worker fit 13/20: param 57 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0057_fold_2.csv mse=83.0325 total=5.6s
Worker fit 14/20: param 57 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0057_fold_3.csv mse=72.9946 total=6.1s
Worker fit 15/20: param 57 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0057_fold_4.csv mse=73.4484 total=6.0s
Worker fit 16/20: param 60 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0060_fold_0.csv mse=87.9888 total=5.8s
Worker fit 17/20: param 60 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0060_fold_1.csv mse=124.6880 total=5.8s
Worker fit 18/20: param 60 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0060_fold_2.csv mse=84.8830 total=5.6s
Worker fit 19/20: param 60 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0060_fold_3.csv mse=74.5827 total=6.0s
Worker fit 20/20: param 60 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0060_fold_4.csv mse=72.7453 total=6.0s
Worker finished in 141.9s
Stage 2 progress: 80/125 complete; session elapsed 9m 34s; avg/new fit 7s; ETA 5m 23s
Stage 2: launching one subprocess for 20 fit(s): param 63 fold 0 -> param 78 fold 4
Worker starting 20 fit(s)
Worker fit 1/20: param 63 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0063_fold_0.csv mse=87.2091 total=11.4s
Worker fit 2/20: param 63 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0063_fold_1.csv mse=127.2669 total=9.7s
Worker fit 3/20: param 63 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0063_fold_2.csv mse=84.8447 total=9.3s
Worker fit 4/20: param 63 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0063_fold_3.csv mse=74.2364 total=9.8s
Worker fit 5/20: param 63 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0063_fold_4.csv mse=73.6842 total=10.3s
Worker fit 6/20: param 72 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0072_fold_0.csv mse=89.7849 total=5.8s
Worker fit 7/20: param 72 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0072_fold_1.csv mse=115.4933 total=5.8s
Worker fit 8/20: param 72 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0072_fold_2.csv mse=84.3674 total=5.6s
Worker fit 9/20: param 72 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0072_fold_3.csv mse=72.6894 total=6.0s
Worker fit 10/20: param 72 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0072_fold_4.csv mse=73.8996 total=6.1s
Worker fit 11/20: param 75 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0075_fold_0.csv mse=88.8880 total=5.8s
Worker fit 12/20: param 75 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0075_fold_1.csv mse=117.4970 total=5.8s
Worker fit 13/20: param 75 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0075_fold_2.csv mse=83.9904 total=5.6s
Worker fit 14/20: param 75 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0075_fold_3.csv mse=72.3400 total=6.0s
Worker fit 15/20: param 75 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0075_fold_4.csv mse=74.5964 total=6.1s
Worker fit 16/20: param 78 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0078_fold_0.csv mse=91.4822 total=5.8s
Worker fit 17/20: param 78 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0078_fold_1.csv mse=118.9439 total=5.8s
Worker fit 18/20: param 78 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0078_fold_2.csv mse=86.0769 total=5.6s
Worker fit 19/20: param 78 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0078_fold_3.csv mse=74.2835 total=6.0s
Worker fit 20/20: param 78 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0078_fold_4.csv mse=74.2628 total=6.2s
Worker finished in 142.1s
Stage 2 progress: 100/125 complete; session elapsed 11m 57s; avg/new fit 7s; ETA 2m 59s
Stage 2: launching one subprocess for 20 fit(s): param 81 fold 0 -> param 96 fold 4
Worker starting 20 fit(s)
Worker fit 1/20: param 81 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0081_fold_0.csv mse=90.6961 total=11.3s
Worker fit 2/20: param 81 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0081_fold_1.csv mse=121.0298 total=9.6s
Worker fit 3/20: param 81 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0081_fold_2.csv mse=85.9051 total=9.2s
Worker fit 4/20: param 81 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0081_fold_3.csv mse=73.5613 total=9.8s
Worker fit 5/20: param 81 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0081_fold_4.csv mse=74.9398 total=10.2s
Worker fit 6/20: param 90 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0090_fold_0.csv mse=89.1484 total=5.8s
Worker fit 7/20: param 90 fold 1
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0090_fold_1.csv mse=115.3934 total=5.7s
Worker fit 8/20: param 90 fold 2
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0090_fold_2.csv mse=84.6502 total=5.6s
Worker fit 9/20: param 90 fold 3
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0090_fold_3.csv mse=73.2269 total=5.9s
Worker fit 10/20: param 90 fold 4
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0090_fold_4.csv mse=74.0244 total=6.0s
Worker fit 11/20: param 93 fold 0
Wrote /home/jamie/storage-1/github-repos/where-my-wifi-kevin/code/eval_results/gp_stage2/param_0093_fold_0.csv mse=88.4625 total=5.8s
Worker fit 12/20: param 93 fold 1

In [9]:

stage2_results = completed_gp_results(STAGE2_RESULT_DIR, grid)
stage2_summary = summarize_cv_results(stage2_results)
stage2_summary = stage2_summary.merge(grid, on="param_id", how="left")
stage2_complete = stage2_summary[stage2_summary["n_folds"] == STAGE2_FOLDS].copy()
stage2_summary.head(25)

,param_id,mean_mse,std_mse,n_folds,mean_fit_elapsed,mean_predict_elapsed,mean_total_elapsed,ls_xy,ls_z,os_xyz,ls_t,os_t,ap_form,ls_ap,os_ap
0,72,87.246924,17.339720,5,4.936885,0.834561,5.871410,0.040,0.25,20,50,0,add,0.25,10.0
1,36,87.281126,19.731619,5,6.980022,1.772672,10.045219,0.035,0.25,20,50,0,add,0.25,10.0
2,90,87.288657,17.131644,5,4.903731,0.795862,5.801117,0.040,0.50,20,50,0,add,0.25,10.0
3,54,87.299750,19.531152,5,4.973888,0.810807,5.888221,0.035,0.50,20,50,0,add,0.25,10.0
4,75,87.462367,18.099614,5,4.939185,0.828987,5.868620,0.040,0.25,20,50,0,add,0.50,10.0
5,93,87.523151,17.887483,5,4.921200,0.806215,5.830599,0.040,0.50,20,50,0,add,0.50,10.0
6,39,87.643794,20.690397,5,4.988151,0.830359,5.918282,0.035,0.25,20,50,0,add,0.50,10.0
7,57,87.745233,20.562092,5,4.925032,0.814084,5.838898,0.035,0.50,20,50,0,add,0.50,10.0
8,0,88.449838,25.428730,5,6.988316,1.808703,10.096492,0.025,0.25,20,50,0,add,0.25,10.0
9,18,88.564130,25.386417,5,6.968622,1.747736,10.037728,0.025,0.50,20,50,0,add,0.25,10.0
10,42,88.841351,21.022039,5,4.984628,0.823789,5.908156,0.035,0.25,25,50,0,add,0.25,10.0
11,60,88.977570,20.998098,5,4.939770,0.806132,5.846169,0.035,0.50,25,50,0,add,0.25,10.0
12,96,88.980623,18.146117,5,4.913403,0.801712,5.815602,0.040,0.50,25,50,0,add,0.25,10.0
13,78,89.009846,18.337825,5,4.952607,0.835440,5.888515,0.040,0.25,25,50,0,add,0.25,10.0
14,3,89.168166,27.157979,5,4.979155,0.814034,5.895939,0.025,0.25,20,50,0,add,0.50,10.0
15,81,89.226437,19.197323,5,6.950316,1.751429,9.995862,0.040,0.25,25,50,0,add,0.50,10.0
16,99,89.254001,18.830589,5,6.967238,1.765772,10.027036,0.040,0.50,25,50,0,add,0.50,10.0
17,21,89.274138,27.085526,5,4.912698,0.824238,5.837744,0.025,0.50,20,50,0,add,0.50,10.0
18,45,89.363998,22.175511,5,7.042032,1.762670,10.111877,0.035,0.25,25,50,0,add,0.50,10.0
19,63,89.448250,22.002076,5,7.001045,1.771523,10.083061,0.035,0.50,25,50,0,add,0.50,10.0
20,6,89.918834,27.650931,5,5.010128,0.815747,5.927226,0.025,0.25,25,50,0,add,0.25,10.0
21,24,89.989635,27.416943,5,4.932817,0.822318,5.856654,0.025,0.50,25,50,0,add,0.25,10.0
22,9,90.598747,29.245826,5,5.020657,0.821452,5.943328,0.025,0.25,25,50,0,add,0.50,10.0
23,27,90.707896,29.196872,5,4.945475,0.815176,5.861623,0.025,0.50,25,50,0,add,0.50,10.0
24,37,91.022890,18.196924,5,4.937512,0.993540,6.131574,0.035,0.25,20,50,0,add,0.25,20.0

In [10]:

if stage2_complete.empty:
    raise RuntimeError("Need at least one complete stage-2 config before final holdout evaluation.")
best_params = stage2_complete.iloc[0]
best_params

param_id                       72
mean_mse                87.246924
std_mse                  17.33972
n_folds                         5
mean_fit_elapsed         4.936885
mean_predict_elapsed     0.834561
mean_total_elapsed        5.87141
ls_xy                        0.04
ls_z                         0.25
os_xyz                         20
ls_t                           50
os_t                            0
ap_form                       add
ls_ap                        0.25
os_ap                        10.0
Name: 0, dtype: object

In [11]:

def load_outer(prefix):
    return {
        "X": jnp.asarray(np.load(SPLIT_ROOT / f"{prefix}_X.npy")),
        "y": jnp.asarray(np.load(SPLIT_ROOT / f"{prefix}_y.npy")),
        "obs_count": jnp.asarray(np.load(SPLIT_ROOT / f"{prefix}_obs_count.npy")),
        "obs_sse": jnp.asarray(np.load(SPLIT_ROOT / f"{prefix}_obs_sse.npy")),
    }

outer_train = load_outer("outer_train")
outer_holdout = load_outer("outer_holdout")

m = make_indoor_outdoor_mean(outer_train["X"], outer_train["y"])
K = make_wifi_kernel(
    ap_form=best_params["ap_form"],
    ls_xy=best_params["ls_xy"],
    ls_z=best_params["ls_z"],
    os_xyz=best_params["os_xyz"],
    ls_t=best_params["ls_t"],
    os_t=best_params["os_t"],
    ls_ap=best_params["ls_ap"],
    os_ap=best_params["os_ap"],
)

gp = GaussianProcess(m, K)
gp.fit(outer_train["X"], outer_train["y"], outer_train["obs_count"], obs_sse=outer_train["obs_sse"])

start = time.time()
chain = gp.gibbs(
    key=jr.PRNGKey(KEY_SEED + 999_999),
    chains=N_CHAINS,
    samples=N_SAMPLES,
    calibration_iters=CALIBRATION_ITERS,
    jitter_factor=JITTER_FACTOR,
)
fit_elapsed = time.time() - start

cov_chains = chain[1][:, BURNIN::THIN, :]
start = time.time()
pred_means, pred_vars = gp.predict(outer_holdout["X"], cov_chains, method=PREDICT_METHOD)
predict_elapsed = time.time() - start

y_hat = pred_means.mean(axis=0)
final_mse = float(jnp.mean((outer_holdout["y"] - y_hat) ** 2))
final_row = {
    "model": "gp",
    "param_id": int(best_params["param_id"]),
    "mse": final_mse,
    "n_train": int(outer_train["X"].shape[0]),
    "n_test": int(outer_holdout["X"].shape[0]),
    "fit_elapsed": float(fit_elapsed),
    "predict_elapsed": float(predict_elapsed),
    "jitter": float(gp.jitter),
    **{col: best_params[col] for col in ["ap_form", "ls_xy", "ls_z", "os_xyz", "ls_t", "os_t", "ls_ap", "os_ap"]},
}
write_result_row(FINAL_RESULT_PATH, final_row)
final_row

{'model': 'gp',
 'param_id': 652,
 'mse': 73.17362976074219,
 'n_train': 2064,
 'n_test': 553,
 'fit_elapsed': 7.942957401275635,
 'predict_elapsed': 1.7508141994476318,
 'jitter': 0.0008801842923276126,
 'ap_form': 'mult',
 'ls_xy': np.float64(0.05),
 'ls_z': np.float64(0.25),
 'os_xyz': np.int64(20),
 'ls_t': np.int64(50),
 'os_t': np.int64(0),
 'ls_ap': np.float64(0.5),
 'os_ap': np.float64(0.0)}